name: Auto PR and Merge

on:
  workflow_dispatch:
  schedule:
    - cron: "0 1 * * *" # Every Day at 18:00 PDT

jobs:
  merge:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout develop branch
      uses: actions/checkout@v2
      with:
        ref: develop

    - name: Configure Git
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'

    - name: Checkout master branch
      run: git checkout master

    - name: Merge develop into master
      run: git merge develop --no-ff --no-edit

    - name: Push changes
      run: git push origin master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
